[tools]
"pipx:jc" = "1.25.7"
claude = "2.1.195"
ctop = "0.7.7"
flux2 = "2.8.8"
fzf = "0.73.1"
gh = "2.95.0"
go = "1.26.4"
jd = "2.5.0"
jq = "1.8.2"
krew = "0.5.0"
kubectl = "1.36.2"
kubectx = "0.11.0"
lazygit = "0.62.2"
mc = "latest"
neovim = "latest"
node = "26.4.0"
prek = "0.4.5"
python = "3.14"
qdns = "0.19.12"
rtk = "0.42.4"
rust = "1.96.0"
terraform = "1.15.7"
terragrunt = "1.0.8"
tree-sitter = "0.26.9"
uv = "0.11.24"

[settings]
idiomatic_version_file_enable_tools = ["python"]
experimental = true

[settings.python]
compile = false
