[settings]
enable_tools = [
  "pipx:jc",
  "ctop",
  "delta",
  "fzf",
  "gh",
  "go",
  "jd",
  "jq",
  "lazygit",
  "mc",
  "neovim",
  "node",
  "prek",
  "python",
  "qdns",
  "rtk",
  "rust",
  "tree-sitter",
  "uv",
  "lazydocker",
]
