gitEmail = 'marius.schuller@ororatech.com'
gitName = 'Marius Schuller'
workDomain = 'ororatech.com'
workUsername = 'marius'
workUsernameWhole = 'marius.schuller'
chezmoiRepo = 'git@gitlab.com:marius.schuller/chezmoi.git'
